import styles from "../styles/Home.module.css";

import Head from "next/head";
import { useEffect, useState } from "react";

function useCompletion(query: string) {
  const [writing, setWriting] = useState<boolean>(false);
  const [answer, setAnswer] = useState<string | null>(null);
  useEffect(() => {
    if (query.length === 0) return;
    let done = false;
    async function getCompletion(query: string) {
      setWriting(true);
      setAnswer(null);
      try {
        const resp = await fetch(`/api/search?query=${encodeURIComponent(query)}`);
        if (!resp.ok) {
          throw new Error(resp.statusText);
        }
        const data = resp.body;
        if (!data) {
          throw new Error("expected the response data to be defined");
        }
        const reader = data.getReader();
        const decoder = new TextDecoder();
        let [_answer, _done] = ["", false];
        while (!_done) {
          if (done) return;
          const chunk = await reader.read();
          _done = chunk.done;
          const text = decoder.decode(chunk.value);
          _answer += text;
          setAnswer(_answer);
        }
      } catch (error) {
        console.log(error);
        setAnswer(null);
      } finally {
        setWriting(false);
      }
    }
    void getCompletion(query);
    return () => {
      done = true;
      setWriting(false);
      setAnswer(null);
    };
  }, [query]);
  return { writing, answer };
}

const Search: React.FC = () => {
  const [inputValue, setInputValue] = useState("");
  const [query, setQuery] = useState("");
  const { writing, answer } = useCompletion(query);
  return (
    <div
      style={{
        marginTop: "0px",
        maxWidth: "100%",
        position: "relative",
        width: "420px",
        zIndex: 9000,
      }}
    >
      <textarea
        value={inputValue}
        placeholder="Onko Putinista tehty etsintäkuulutus?"
        onChange={(event) => {
          setInputValue(event.target.value);
        }}
        onKeyDown={(event) => {
          if (event.code === "Enter") {
            event.preventDefault();
            setQuery(inputValue);
          }
        }}
        style={{
          background: "hsl(0, 0%, 100%, 0.24)",
          border: "2px solid hsl(0, 0%, 100%, 0.64)",
          borderRadius: "8px",
          color: "white",
          fontFamily: "inherit",
          fontSize: "1rem",
          height: "256px",
          padding: "8px",
          resize: "none",
          width: "100%",
        }}
      />
      {writing || answer ? (
        <div>
          <div
            style={{
              background: "hsl(0, 0%, 100%, 0.24)",
              border: "2px solid hsl(0, 0%, 100%, 0.08)",
              borderRadius: "8px",
              color: "white",
              display: "flex",
              flexDirection: "column",
              fontSize: "1rem",
              gap: "6px",
              marginTop: "24px",
              padding: "12px",
              width: "100%",
            }}
          >
            <span
              style={{
                fontSize: "0.8rem",
                fontWeight: 500,
                opacity: 0.5,
                textTransform: "uppercase",
              }}
            >
              Bot
            </span>
            <span>
              {answer}
              {writing ? (
                <span
                  style={{
                    background: "white",
                    display: "inline-block",
                    height: "18px",
                    marginBottom: "-3px",
                    marginLeft: "4px",
                    width: "8px",
                  }}
                />
              ) : null}
            </span>
          </div>
        </div>
      ) : null}
    </div>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <span style={{ fontSize: "3.6rem", fontWeight: 500 }}>NewsGPT</span>
          <div className={styles.thirteen}>
            <span style={{ fontSize: "2.4rem", fontWeight: 500 }}>AI</span>
          </div>
        </div>
        <Search />
      </main>
    </>
  );
}
