import styles from "../styles/Home.module.css";

import Head from "next/head";
import { useState } from "react";

type SearchResult = {
  answer: string;
  stories: { publication: string; headline: string; href: string }[];
};

const Search: React.FC = () => {
  const [query, setQuery] = useState("");
  // execute searches
  const [searching, setSearching] = useState(false);
  const [result, setResult] = useState<SearchResult | null>(null);
  async function doSearch() {
    try {
      setSearching(true);
      setResult(null);
      const resp = await fetch(`/api/search?query=${encodeURIComponent(query)}`);
      const data = (await resp.json()) as SearchResult;
      setSearching(false);
      setResult(data);
    } catch (error) {
      console.log(error);
    }
  }
  return (
    <div
      style={{
        marginTop: "0px",
        maxWidth: "100%",
        position: "relative",
        width: "420px",
        zIndex: 9000,
      }}
    >
      <textarea
        value={query}
        placeholder="Onko Putinista tehty etsintäkuulutus?"
        onChange={(event) => {
          setQuery(event.target.value);
        }}
        onKeyDown={(event) => {
          if (event.code === "Enter") {
            event.preventDefault();
            void doSearch();
          }
        }}
        style={{
          background: "hsl(0, 0%, 100%, 0.24)",
          border: "2px solid hsl(0, 0%, 100%, 0.64)",
          borderRadius: "8px",
          color: "white",
          fontFamily: "inherit",
          fontSize: "1rem",
          height: "96px",
          padding: "8px",
          resize: "none",
          width: "100%",
        }}
      />
      {result ? (
        <div>
          <div
            style={{
              background: "hsl(0, 0%, 100%, 0.24)",
              border: "2px solid hsl(0, 0%, 100%, 0.08)",
              borderRadius: "8px",
              color: "white",
              display: "flex",
              flexDirection: "column",
              fontSize: "1rem",
              gap: "6px",
              marginTop: "24px",
              padding: "12px",
              width: "100%",
            }}
          >
            <span
              style={{
                fontSize: "0.8rem",
                fontWeight: 500,
                opacity: 0.5,
                textTransform: "uppercase",
              }}
            >
              Bot
            </span>
            <span>{result.answer}</span>
          </div>
          <ol
            style={{
              background: "hsl(0, 0%, 100%, 0.24)",
              border: "2px solid hsl(0, 0%, 100%, 0.08)",
              borderRadius: "8px",
              color: "white",
              display: "flex",
              flexDirection: "column",
              fontSize: "1rem",
              gap: "20px",
              listStyle: "none",
              margin: "24px 0px 0px 0px",
              padding: "12px",
              width: "100%",
            }}
          >
            {result.stories.map((story) => (
              <li
                key={story.href}
                style={{
                  display: "flex",
                  flexDirection: "column",
                  gap: "4px",
                }}
              >
                <span
                  style={{
                    fontSize: "0.8rem",
                    fontWeight: 500,
                    opacity: 0.5,
                    textTransform: "uppercase",
                  }}
                >
                  Story
                </span>
                <a href={story.href} target="_blank">
                  {story.headline}
                </a>
              </li>
            ))}
          </ol>
        </div>
      ) : null}
    </div>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <span style={{ fontSize: "3.6rem", fontWeight: 500 }}>NewsGPT</span>
          <div className={styles.thirteen}>
            <span style={{ fontSize: "2.4rem", fontWeight: 500 }}>AI</span>
          </div>
        </div>
        <Search />
      </main>
    </>
  );
}
